# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy as np
print("Версия numpy:", np.__version__)


Версия numpy: 1.26.4


2) Создать нулевой вектор размера 10

In [ ]:
zero = np.zeros(10)
print("Нулевой вектор размера 10:", zero)

Нулевой вектор размера 10: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [ ]:
seven = np.full(7, 7)
print("Вектор, заполненный семерками размера 7:", seven)

Вектор, заполненный семерками размера 7: [7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
vector = np.arange(10, 101, 2)
print("Вектор, заполненный четными числами от 10 до 100:", vector)

Вектор, заполненный четными числами от 10 до 100: [ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
random_array = np.random.randint(1, 11, size=10)
reversed_array = random_array[::-1]
print("Случайный массив (числа от 1 до 10):", random_array)
print("Развернутый массив:", reversed_array)


Случайный массив (числа от 1 до 10): [ 2  6  5  5  1  3  2 10  6  4]
Развернутый массив: [ 4  6 10  2  3  1  5  5  6  2]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
matrix = np.arange(9).reshape(3, 3)
print("Матрица 3x3, заполненная числами от 0 до 9:")
print(matrix)

Матрица 3x3, заполненная числами от 0 до 9:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
matrix = np.eye(4, k=1)
print("Матрица 4x4 с единицами на диагонали, смещенной на один вверх:")
print(matrix)

Матрица 4x4 с единицами на диагонали, смещенной на один вверх:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
matrix_7_fill = np.full((4, 4), 7)
np.fill_diagonal(matrix_7_fill, [1, 2, 3, 4])
print("Матрица с числами от 1 до 4 по диагонали, остальное заполнено семерками:")
print(matrix_7_fill)


Матрица с числами от 1 до 4 по диагонали, остальное заполнено семерками:
[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
matrix_5x5 = np.tile(np.arange(5), (5, 1))
print("Матрица 5x5, заполненная числами от 0 до 4 по строкам:")
print(matrix_5x5)

Матрица 5x5, заполненная числами от 0 до 4 по строкам:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
matrix_random_10x10 = np.random.randint(1, 11, size=(10, 10))
matrix_centered_by_rows = matrix_random_10x10 - matrix_random_10x10.mean(axis=1, keepdims=True)
print("Матрица 10x10 (числа от 1 до 10), из которой вычтено среднее по строкам:")
print(matrix_centered_by_rows)


Матрица 10x10 (числа от 1 до 10), из которой вычтено среднее по строкам:
[[-1.8  3.2 -3.8  4.2  2.2  0.2 -0.8 -2.8 -0.8  0.2]
 [-1.1  3.9  3.9  0.9 -5.1 -4.1  2.9  0.9 -4.1  1.9]
 [-0.7  1.3  4.3 -4.7 -0.7  0.3  3.3  2.3 -2.7 -2.7]
 [ 5.   1.  -2.  -2.   3.   0.  -2.   1.  -2.  -2. ]
 [ 4.2 -1.8 -3.8 -2.8  1.2  0.2  4.2 -0.8 -2.8  2.2]
 [ 2.6  0.6  3.6 -1.4 -0.4  1.6 -0.4 -1.4 -1.4 -3.4]
 [-3.1 -1.1 -3.1  1.9  1.9 -1.1  3.9  4.9 -2.1 -2.1]
 [ 3.9  0.9  1.9 -3.1 -4.1  1.9 -0.1 -0.1  2.9 -4.1]
 [ 3.6 -3.4 -3.4  3.6  3.6  4.6 -0.4 -2.4 -3.4 -2.4]
 [ 3.8 -5.2  3.8  0.8  0.8 -1.2  1.8 -1.2 -0.2 -3.2]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
matrix_random_10x10_2 = np.random.randint(1, 11, size=(10, 10))
matrix_centered_by_columns = matrix_random_10x10_2 - np.median(matrix_random_10x10_2, axis=0, keepdims=True)
print("Матрица 10x10 (числа от 1 до 10), из которой вычтена медиана по столбцам:")
print(matrix_centered_by_columns)

Матрица 10x10 (числа от 1 до 10), из которой вычтена медиана по столбцам:
[[ 2.   0.  -1.5  1.  -0.5 -1.5 -3.   3.5  4.  -7.5]
 [ 0.  -2.  -4.5 -2.   5.5 -2.5 -3.   0.5 -4.  -4.5]
 [ 0.   0.  -2.5  2.  -0.5  0.5  4.  -2.5  0.   1.5]
 [-1.  -5.  -0.5 -5.   0.5 -0.5  0.   2.5 -1.   0.5]
 [-3.  -6.   1.5 -7.   1.5  2.5 -2.  -4.5  3.   1.5]
 [-4.   1.   0.5  0.  -3.5  2.5  0.   2.5  0.  -4.5]
 [ 0.   1.  -1.5  1.   1.5 -4.5  4.  -0.5  3.   0.5]
 [ 1.  -4.   2.5 -5.  -1.5 -3.5 -4.  -0.5  3.  -0.5]
 [-6.   0.   2.5  0.   4.5  2.5  0.  -3.5 -2.   1.5]
 [ 1.   0.   0.5  0.  -2.5  2.5  3.   0.5 -2.  -1.5]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
matrix_random_5x5 = np.random.randint(1, 11, size=(5, 5))
max_columns = matrix_random_5x5.max(axis=1).reshape(-1, 1)
min_columns = matrix_random_5x5.min(axis=1).reshape(-1, 1)
matrix_extended = np.hstack((matrix_random_5x5, max_columns, min_columns))
print("Матрица 5x5 (числа от 1 до 10) с добавленными столбцами максимумов и минимумов по строкам:")
print(matrix_extended)

Матрица 5x5 (числа от 1 до 10) с добавленными столбцами максимумов и минимумов по строкам:
[[ 8  4  2  1  2  8  1]
 [ 5 10  1  8  7 10  1]
 [10  2  4  3  3 10  2]
 [ 4  7  4  3  7  7  3]
 [ 2 10 10  6  5 10  2]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [ ]:
vector = np.arange(1, 52)

odd_numbers = vector[vector % 2 != 0]
even_numbers = vector[vector % 2 == 0]

ven_matrix = even_numbers[:10].reshape(5, 2)

odd_matrix = odd_numbers[:10].reshape(2, 5)

product = np.dot(ven_matrix, odd_matrix)

print("Произведение матриц:\n", product)

try:
    inverse_product = np.linalg.inv(product)
    print("Обратная матрица произведения:\n", inverse_product)
except np.linalg.LinAlgError:
    print("Обратная матрица не существует.")

Произведение матриц:
 [[ 46  58  70  82  94]
 [ 94 122 150 178 206]
 [142 186 230 274 318]
 [190 250 310 370 430]
 [238 314 390 466 542]]
Обратная матрица не существует.


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
chessboard_matrix = np.zeros((8, 8), dtype=int)
chessboard_matrix[1::2, ::2] = 1
chessboard_matrix[::2, 1::2] = 1
print("8x8 матрица, заполненная в шахматном порядке:")
print(chessboard_matrix)

8x8 матрица, заполненная в шахматном порядке:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
